--!strict

local Config = {
	Version = "0.2.0-alpha",

	World = {
		RootName = "PannaDistrict",
		FieldStyle = "NaturalGrassFootballV1",
		LobbyOrigin = Vector3.new(0, 0, -165),
		LobbySpawn = CFrame.new(0, 4, -170),
		MinimumArenaCount = 6,
		ArenaPositions = {
			CFrame.new(-58, 0, -75),
			CFrame.new(58, 0, -75),
			CFrame.new(-58, 0, 25),
			CFrame.new(58, 0, 25),
			CFrame.new(-58, 0, 125),
			CFrame.new(58, 0, 125),
		},
		ArenaWidth = 48,
		ArenaLength = 76,
		FenceHeight = 16,
		GoalWidth = 16,
		GoalHeight = 8,
		GoalDepth = 5,
	},

	Rooms = {
		InteractionDistance = 16,
		WaitingTimeoutSeconds = 120,
	},

	Match = {
		CountdownSeconds = 4,
		DurationSeconds = 150,
		OvertimeSeconds = 45,
		GoalLimit = 5,
		GoalResetSeconds = 2.5,
		ResultSeconds = 6,
		EarlyForfeitSeconds = 15,
		GoldenGoalInOvertime = true,
		PannaPoints = 1,
		PannaInstantWin = false,
	},

	Ball = {
		Radius = 1.15,
		Density = 0.835,
		Friction = 0.45,
		Elasticity = 0.3,
		ResetBelowY = -18,
		InteractionRadius = 8,

		Capture = {
			Radius = 5.8,
			MaximumHeight = 4.3,
			FrontDistance = 5.5,
			RearAllowance = 0.65,
			LateralDistance = 3.25,
			MaximumBallSpeed = 38,
			OwnerBreakRadius = 6.2,
			OwnerFrontDistance = 6,
			OwnerRearAllowance = 3.6,
			OwnerLateralDistance = 4.7,
			MaximumControlledBallSpeed = 66,
			OwnerRetentionBonus = 0.18,
			ControlGraceBonus = 0.2,
			ContestedScoreMargin = 0.12,
			ContestedSeconds = 0.14,
			ControlGraceSeconds = 0.14,
			AirSettleGraceSeconds = 0.34,
			ControlLossRecaptureSeconds = 0.16,
			DistanceWeight = 0.55,
			FrontWeight = 0.25,
			ApproachWeight = 0.2,
			ApproachSpeed = 24,
		},

		FirstTouch = {
			BufferSeconds = 0.9,
			MaximumRevisionAdvance = 3,
			Radius = 6.3,
			MaximumHeight = 4.6,
			SoftSpeed = 44,
			HardSpeed = 74,
			BufferedScoreBonus = 0.18,
		},
		ResetHoldSeconds = 0.28,

		Dribble = {
			IdleDistance = 2.3,
			WalkDistance = 2.65,
			SprintDistance = 3.15,
			ShieldDistance = 1.95,
			HeightOffset = 0.09,
			GroundProbeHeight = 3,
			GroundProbeDistance = 8,
			GroundNormalMinimumY = 0.55,
			WalkSpeedThreshold = 2,
			SprintSpeed = 20.5,
			NaturalFrequency = 8,
			DampingRatio = 1,
			VelocityCarry = 1,
			MaximumCorrectionSpeed = 30,
			MaximumAccelerationWalk = 135,
			MaximumAccelerationSprint = 170,
			ShieldAccelerationMultiplier = 0.8,
			AirControlMultiplier = 0.28,
			MaximumAirControlHeight = 2.6,
			MaximumTargetError = 6,
			DirectionTurnRateDegrees = 620,
			CaptureHorizontalDamping = 0.78,
			CaptureVerticalDamping = 0.72,
			MaximumCaptureDeltaSpeed = 36,
			GroundAdhesionAcceleration = 12,
			ForceDeadZone = 0.06,
			ObstacleRadiusScale = 0.94,
			ObstacleClearance = 0.08,
			BlockedLossSeconds = 0.24,
			RollResponsiveness = 16,
			MaximumRollAngularAcceleration = 80,
		},

		Spin = {
			MinimumCurveSpeed = 18,
			MinimumYawRate = 0.35,
			MagnusCoefficient = 0.013,
			MaximumCurveAcceleration = 8,
			GroundCurveMultiplier = 0.25,
		},

		Shot = {
			ChargeSeconds = 1.1,
			MinimumPower = 0.1,
			PowerExponent = 1,
			PlayerVelocityCarry = 0.2,
			StateSeconds = 0.14,
			ShooterRecaptureSeconds = 0.58,
			SideSpinMaximum = 6.5,
			AngularVelocityScale = 0.4,
			Types = {
				Low = {
					SpeedMinimum = 34,
					SpeedMaximum = 74,
					LiftMinimum = 1.4,
					LiftMaximum = 3.8,
					RollSpin = 10,
					SideSpinMultiplier = 0.75,
				},
				Normal = {
					SpeedMinimum = 36,
					SpeedMaximum = 82,
					LiftMinimum = 3,
					LiftMaximum = 12.5,
					RollSpin = 7,
					SideSpinMultiplier = 1,
				},
				Chip = {
					SpeedMinimum = 28,
					SpeedMaximum = 62,
					LiftMinimum = 12,
					LiftMaximum = 25,
					RollSpin = -8,
					SideSpinMultiplier = 0.45,
				},
			},
		},

		Pass = {
			ChargeSeconds = 0.9,
			MinimumPower = 0.1,
			PowerExponent = 1.05,
			SpeedMinimum = 28,
			SpeedMaximum = 58,
			LiftMinimum = 1,
			LiftMaximum = 3.6,
			PlayerVelocityCarry = 0.18,
			StateSeconds = 0.14,
			RollSpin = 9,
			AngularVelocityScale = 0.3,
			ShooterRecaptureSeconds = 0.42,
		},

		Trail = {
			EnabledSpeed = 34,
			DisabledSpeed = 27,
			Lifetime = 0.16,
			WidthStart = 0.42,
			WidthEnd = 0,
		},

		Limits = {
			MaximumSpeed = 96,
			MaximumVerticalSpeed = 68,
			MaximumAngularSpeed = 52,
			MinimumFlightSeconds = 0.16,
			BoundaryCheckSeconds = 0.16,
			BounceVerticalSpeed = 5.5,
			BounceStateSeconds = 0.2,
			FiniteMagnitude = 100000,
		},
	},

	Actions = {
		KickCooldown = 0.28,
		PassCooldown = 0.35,
		TrapCooldown = 0.2,
		ChargeStartCooldown = 0.04,
		TackleCooldown = 1.2,
		SkillCooldown = 2.0,
		DashCooldown = 3.0,
		FeintCooldown = 1.1,
		ShieldToggleCooldown = 0.15,
		DashSpeed = 44,
		DashSeconds = 0.22,
		Tackle = {
			PlayerRadius = 6.2,
			BallRadius = 4.6,
			MaximumHeight = 4.2,
			AttackerForwardDot = 0.48,
			DefenderFrontDot = 0.05,
			ImpulseSpeed = 27,
			Lift = 2.2,
			AngularVelocityScale = 0.32,
			ReleaseSeconds = 0.16,
			FeintVulnerabilityRadiusBonus = 0.75,
			FeintVulnerabilityDotBonus = 0.18,
		},

		Feint = {
			LateralMaximum = 1,
			VulnerabilityStart = 0.16,
			VulnerabilityEnd = 0.52,
			Variants = {
				StepOver = {
					Duration = 0.42,
					DistanceMultiplier = 0.96,
					LateralDistance = 0.8,
					ControlAccelerationMultiplier = 0.82,
				},
				Cut = {
					Duration = 0.34,
					DistanceMultiplier = 1.16,
					LateralDistance = 1.3,
					ControlAccelerationMultiplier = 0.9,
				},
				DragBack = {
					Duration = 0.48,
					DistanceMultiplier = 0.78,
					LateralDistance = 0.35,
					ControlAccelerationMultiplier = 0.72,
				},
				Roulette = {
					Duration = 0.58,
					DistanceMultiplier = 0.88,
					LateralDistance = 1.5,
					ControlAccelerationMultiplier = 0.76,
				},
			},
		},

		Shield = {
			Radius = 5.5,
			MaximumSeconds = 2.5,
			TackleFrontDot = 0.35,
		},

		Panna = {
			Radius = 7.2,
			MinimumDistance = 1.4,
			AimDot = 0.86,
			AttackerFacingDot = 0.45,
			CorridorRadius = 1.45,
			Speed = 33,
			Lift = 1.25,
			AngularVelocityScale = 0.32,
			ShooterRecaptureSeconds = 0.58,
			ReleaseSeconds = 0.3,
		},
	},

	Security = {
		RemoteBurst = 12,
		RemoteRefillPerSecond = 8,
		MaxDirectionMagnitudeError = 0.12,
		MaxCharacterDistanceFromArena = 32,
		Command = {
			MaximumPastSeconds = 1.5,
			MaximumFutureSeconds = 0.35,
			MaximumSequenceJump = 100000,
			MinimumAimFacingDot = -0.05,
			MaximumContactHeight = 4.6,
		},
		Movement = {
			SampleInterval = 0.1,
			WindowSeconds = 1,
			ShortSlack = 7,
			WindowSlack = 9,
			VerticalSlack = 8,
			ViolationWindow = 4,
			ViolationsBeforeRespawn = 3,
			IntruderScanInterval = 0.12,
			MaximumCarrierSpeed = 52,
		},
	},

	Rewards = {
		ParticipationCoins = 15,
		WinCoins = 45,
		GoalCoins = 4,
		PannaCoins = 10,
		ParticipationXP = 25,
		WinXP = 60,
		StartingRating = 1000,
		RatingK = 24,
	},

	DataStore = {
		Name = "PannaPlayerData_v1",
		SchemaVersion = 1,
		Retries = 3,
		RetryDelaySeconds = 1.5,
		AutosaveSeconds = 90,
		RecentRewardIds = 24,
		SessionLeaseSeconds = 180,
		SaveLockWaitSeconds = 10,
		ShutdownTimeoutSeconds = 25,
	},
}

return table.freeze(Config)
