--!strict

local Config = {
	Version = "0.3.0-alpha",

	World = {
		RootName = "PannaDistrict",
		FieldStyle = "BrightBlockFootballV1",
		LobbyOrigin = Vector3.new(0, 0, -165),
		LobbySpawn = CFrame.new(0, 4, -170),
		MinimumArenaCount = 6,
		ArenaPositions = {
			CFrame.new(-58, 0, -75),
			CFrame.new(58, 0, -75),
			CFrame.new(-58, 0, 25),
			CFrame.new(58, 0, 25),
			CFrame.new(-58, 0, 125),
			CFrame.new(58, 0, 125),
		},
		ArenaWidth = 48,
		ArenaLength = 76,
		FenceHeight = 16,
		GoalWidth = 16,
		GoalHeight = 8,
		GoalDepth = 5,
	},

	Rooms = {
		InteractionDistance = 16,
		WaitingTimeoutSeconds = 120,
	},

	Match = {
		CountdownSeconds = 3,
		DurationSeconds = 90,
		OvertimeSeconds = 30,
		GoalLimit = 3,
		GoalResetSeconds = 2.5,
		ResultSeconds = 5,
		EarlyForfeitSeconds = 15,
		GoldenGoalInOvertime = true,
		PannaPoints = 1,
		PannaInstantWin = false,
	},

	Ball = {
		Radius = 1.15,
		VisualVersion = "SoccerPanelsV1",
		MechanicsVersion = "StreetControlV3",
		Density = 0.835,
		Friction = 0.45,
		Elasticity = 0.3,
		ResetBelowY = -18,
		InteractionRadius = 8,

		Capture = {
			Radius = 5.8,
			MaximumHeight = 4.3,
			FrontDistance = 5.5,
			RearAllowance = 0.65,
			LateralDistance = 3.25,
			MaximumBallSpeed = 38,
			OwnerBreakRadius = 6.2,
			OwnerFrontDistance = 6,
			OwnerRearAllowance = 3.6,
			OwnerLateralDistance = 4.7,
			MaximumControlledBallSpeed = 66,
			OwnerRetentionBonus = 0.18,
			ControlGraceBonus = 0.2,
			ContestedScoreMargin = 0.12,
			ContestedSeconds = 0.14,
			ControlGraceSeconds = 0.14,
			AirSettleGraceSeconds = 0.34,
			ControlLossRecaptureSeconds = 0.16,
			DistanceWeight = 0.55,
			FrontWeight = 0.25,
			ApproachWeight = 0.2,
			ApproachSpeed = 24,
		},

		FirstTouch = {
			BufferSeconds = 0.9,
			MaximumRevisionAdvance = 3,
			Radius = 6.3,
			MaximumHeight = 4.6,
			SoftSpeed = 44,
			HardSpeed = 74,
			BufferedScoreBonus = 0.18,
			RedirectHorizontalRetention = 0.16,
			RedirectVerticalRetention = 0.08,
			TrapHorizontalRetention = 0.03,
			TrapVerticalRetention = 0,
			MaximumExitSpeed = 32,
		},
		ResetHoldSeconds = 0.28,

		Dribble = {
			IdleDistance = 2.15,
			WalkDistance = 2.55,
			SprintDistance = 3.35,
			ShieldDistance = 1.95,
			HeightOffset = 0.09,
			GroundProbeHeight = 3,
			GroundProbeDistance = 8,
			GroundNormalMinimumY = 0.55,
			WalkSpeedThreshold = 2,
			SprintSpeed = 20.5,
			NaturalFrequency = 8.5,
			DampingRatio = 1.05,
			VelocityCarry = 1,
			MaximumCorrectionSpeed = 32,
			MaximumAccelerationWalk = 145,
			MaximumAccelerationSprint = 185,
			ShieldAccelerationMultiplier = 0.8,
			AirControlMultiplier = 0.28,
			MaximumAirControlHeight = 2.6,
			MaximumTargetError = 6,
			DirectionTurnRateDegrees = 720,
			MaximumCaptureDeltaSpeed = 36,
			GroundAdhesionAcceleration = 14,
			ForceDeadZone = 0.06,
			ObstacleRadiusScale = 0.94,
			ObstacleClearance = 0.08,
			BlockedLossSeconds = 0.24,
			RollResponsiveness = 16,
			MaximumRollAngularAcceleration = 80,
		},

		Spin = {
			MinimumCurveSpeed = 18,
			MinimumYawRate = 0.35,
			MagnusCoefficient = 0.013,
			MaximumCurveAcceleration = 8,
			GroundCurveMultiplier = 0.25,
		},

		Aerodynamics = {
			DragCoefficient = 0.0022,
			MaximumDragAcceleration = 18,
			MaximumStepSeconds = 0.05,
		},

		Shot = {
			ChargeSeconds = 1.1,
			MinimumPower = 0.1,
			PowerExponent = 1.1,
			PlayerVelocityCarry = 0.2,
			StateSeconds = 0.14,
			ShooterRecaptureSeconds = 0.58,
			SideSpinMaximum = 10,
			AimAssist = {
				ConeDot = 0.72,
				Strength = 0.2,
				SpinTargetFraction = 0.18,
			},
			Types = {
				Low = {
					SpeedMinimum = 34,
					SpeedMaximum = 78,
					LiftMinimum = 2.4,
					LiftMaximum = 6,
					RollRatio = 0.88,
					SideSpinMultiplier = 0.75,
					AimAssistMultiplier = 0.78,
				},
				Normal = {
					SpeedMinimum = 38,
					SpeedMaximum = 84,
					LiftMinimum = 9,
					LiftMaximum = 27,
					RollRatio = 0.72,
					SideSpinMultiplier = 1,
					AimAssistMultiplier = 1,
				},
				Chip = {
					SpeedMinimum = 30,
					SpeedMaximum = 60,
					LiftMinimum = 26,
					LiftMaximum = 49,
					RollRatio = -0.18,
					SideSpinMultiplier = 0.45,
					AimAssistMultiplier = 0.84,
				},
			},
		},

		Pass = {
			ChargeSeconds = 0.9,
			MinimumPower = 0.1,
			PowerExponent = 1.08,
			SpeedMinimum = 24,
			SpeedMaximum = 56,
			LiftMinimum = 0.4,
			LiftMaximum = 1.8,
			PlayerVelocityCarry = 0.18,
			MovementAssistMinimumSpeed = 3,
			MovementAssistConeDot = -0.15,
			MovementAssistStrength = 0.2,
			StateSeconds = 0.14,
			RollRatio = 0.92,
			ShooterRecaptureSeconds = 0.32,
		},

		Trail = {
			EnabledSpeed = 68,
			DisabledSpeed = 60,
			Lifetime = 0.08,
			WidthStart = 0.2,
			WidthEnd = 0,
		},

		Limits = {
			MaximumSpeed = 96,
			MaximumVerticalSpeed = 68,
			MaximumAngularSpeed = 90,
			MinimumFlightSeconds = 0.16,
			BoundaryCheckSeconds = 0.16,
			BounceVerticalSpeed = 5.5,
			BounceStateSeconds = 0.2,
			FiniteMagnitude = 100000,
		},
	},

	Actions = {
		KickCooldown = 0.28,
		PassCooldown = 0.28,
		TrapCooldown = 0.2,
		ChargeStartCooldown = 0.04,
		ChargeMaximumSeconds = 4,
		TackleCooldown = 0.9,
		SkillCooldown = 2.0,
		DashCooldown = 3.0,
		FeintCooldown = 0.95,
		ShieldToggleCooldown = 0.15,
		DashSpeed = 44,
		DashSeconds = 0.22,
		Tackle = {
			PlayerRadius = 6.6,
			BallRadius = 5.2,
			MaximumHeight = 4.2,
			AttackerForwardDot = 0.25,
			DefenderMinimumDot = -0.55,
			TakeoverGraceSeconds = 0.34,
			MaximumStopDeltaSpeed = 42,
			MaximumStopAngularSpeed = 90,
		},

		Feint = {
			LateralMaximum = 1,
			ProtectionBreakRadius = 5.8,
			HoldNaturalFrequency = 12,
			HoldDampingRatio = 1.25,
			HoldMaximumCorrectionSpeed = 20,
			HoldMaximumAcceleration = 260,
			MaximumStopDeltaSpeed = 48,
			MaximumStopAngularSpeed = 90,
			Variants = {
				StepOver = {
					Duration = 0.48,
				},
				Cut = {
					Duration = 0.42,
				},
				DragBack = {
					Duration = 0.5,
				},
				Roulette = {
					Duration = 0.58,
				},
			},
		},

		Shield = {
			Radius = 5.5,
			MaximumSeconds = 2.5,
			TackleFrontDot = 0.35,
		},

		Panna = {
			Radius = 7.2,
			MinimumDistance = 1.4,
			AimDot = 0.82,
			AttackerFacingDot = 0.45,
			DefenderFacingDot = -0.15,
			CorridorRadius = 1.55,
			AimAssistStrength = 0.65,
			Speed = 34,
			Lift = 1.25,
			RollRatio = 0.95,
			ShooterRecaptureSeconds = 0.4,
			ReleaseSeconds = 0.3,
		},
	},

	VisualEffects = {
		Version = "StreetReadabilityV1",
		Enabled = true,
		MaximumTransientParts = 56,
		AimGuide = {
			IdleLength = 7.5,
			ChargedLength = 13.5,
			Width = 0.13,
			ChargedWidth = 0.22,
			TrajectoryDots = 8,
		},
		BallDirection = {
			MinimumSpeed = 14,
			MinimumLength = 4.5,
			MaximumLength = 13,
			SpeedToLength = 0.14,
			Width = 0.11,
		},
		Impact = {
			ShortLifetime = 0.28,
			Lifetime = 0.42,
			CelebrationLifetime = 0.72,
		},
	},

	Security = {
		RemoteBurst = 12,
		RemoteRefillPerSecond = 8,
		MaxDirectionMagnitudeError = 0.12,
		MaxCharacterDistanceFromArena = 32,
		Command = {
			MaximumPastSeconds = 1.5,
			MaximumFutureSeconds = 0.35,
			MaximumSequenceJump = 100000,
			MinimumAimFacingDot = -0.05,
			MaximumContactHeight = 4.6,
		},
		Movement = {
			SampleInterval = 0.1,
			WindowSeconds = 1,
			ShortSlack = 7,
			WindowSlack = 9,
			VerticalSlack = 8,
			ViolationWindow = 4,
			ViolationsBeforeRespawn = 3,
			IntruderScanInterval = 0.12,
			MaximumCarrierSpeed = 52,
		},
	},

	Rewards = {
		ParticipationCoins = 15,
		WinCoins = 45,
		GoalCoins = 4,
		PannaCoins = 10,
		ParticipationXP = 25,
		WinXP = 60,
		StartingRating = 1000,
		RatingK = 24,
	},

	DataStore = {
		Name = "PannaPlayerData_v1",
		SchemaVersion = 1,
		Retries = 3,
		RetryDelaySeconds = 1.5,
		AutosaveSeconds = 90,
		RecentRewardIds = 24,
		SessionLeaseSeconds = 180,
		SaveLockWaitSeconds = 10,
		ShutdownTimeoutSeconds = 25,
	},
}

return table.freeze(Config)
